services:
  frontend:
    build: ./client      
    ports:
      - "3000:80"
    networks:
      - ecommerce-net

  backend:
    build: ./backend     
    ports:
      - "5000:5000"
    networks:
      - ecommerce-net
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/yolomy

  db:
    image: mongo:6
    volumes:
      - mongo-data:/data/db
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  mongo-data: