---
- name: Frontend deployment
  block:

    - name: Build frontend Docker image
      docker_image:
        name: "{{ frontend_image }}"
        source: build
        build:
          path: "{{ repo_dest }}/client"

    - name: Run frontend container
      docker_container:
        name: "{{ frontend_container_name }}"
        image: "{{ frontend_image }}"
        state: started
        restart_policy: always

        ports:
          - "{{ frontend_port }}"

        networks:
          - name: "{{ frontend_network }}"

  tags:
    - frontend
    - deployment