---
- name: Backend deployment
  block:

    - name: Build backend Docker image
      docker_image:
        name: "{{ backend_image }}"
        source: build
        build:
          path: "{{ repo_dest }}/backend"

    - name: Run backend container
      docker_container:
        name: "{{ backend_container_name }}"
        image: "{{ backend_image }}"
        state: started
        restart_policy: always

        ports:
          - "{{ backend_port }}"

        env:
          MONGODB_URI: "{{ mongodb_uri }}"

        networks:
          - name: "{{ backend_network }}"

  tags:
    - backend
    - deployment